# https://eslint.org/docs/user-guide/configuring/

# 共有（JS/TS）
env:
  browser: true # document や console にエラーが出ないようにする
  node: true # document や console にエラーが出ないようにする
  es6: true
extends:
  - eslint:recommended
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules:
  no-var: warn
# TS向け
overrides:
  - files:
      - "*.ts"
      - "*.tsx"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: ./tsconfig.json
      sourceType: module
    plugins:
      - "@typescript-eslint"
    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - prettier/@typescript-eslint
